STORM_B add printer page to admin
Shabaldas/storm_esbuild pull request #213
Opened 2023-07-24 06:41 UTC by AndriiBuhalo

2023-07-24 06:43 UTC, AndriiBuhalo commented
Don't work update printer. I don't understand why i can't stand up in method update(

2023-08-06 21:23 UTC, Shabaldas commented on app/views/dredd/products/_product_option_color_values_form.erb
> +z<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
z???
smells russian swastika 😄

2023-08-06 21:32 UTC, Shabaldas requested changes
Please change this issues, and after that we come back.
And please update your description 🥺 
Where is pictures?
Don't forget that this is not simple PR, this is a document 🙏

2023-08-06 21:32 UTC, Shabaldas commented on app/views/dredd/products/_form.html.erb
> -          <%= primary_option.check_box :primary, { checked: true }, true, false  %>
but why???
DON'T TOUCH PRODUCT

please.

2023-08-06 21:32 UTC, Shabaldas commented on app/views/dredd/products/_form.html.erb
> -          <%= primary_option.hidden_field :option_id, value: Option.last.id %>
leave like before

2023-08-06 21:32 UTC, Shabaldas commented on app/views/dredd/products/_form.html.erb
> -          <%= secondary_option.label t("dredd.products.secondary") %>
leave like before

2023-08-06 21:32 UTC, Shabaldas commented on app/views/dredd/products/_form.html.erb
> -          <%= secondary_option.hidden_field :option_id, value: Option.first.id %>
leave like before

2023-08-06 21:32 UTC, Shabaldas commented on config/locales/simple_form.en.yml
> +en:
remove all this file

2023-08-06 21:32 UTC, Shabaldas commented on lib/templates/erb/scaffold/_form.html.erb
> +<%# frozen_string_literal: true %>
remove all this file

2023-08-06 21:32 UTC, Shabaldas commented on app/controllers/dredd/printer_maintenances_controller.rb
> +# frozen_string_literal: true
so we discuss to use only one controller, why do you need this one?

2023-08-06 21:32 UTC, Shabaldas commented on app/controllers/dredd/printers_controller.rb
> +      @printer = Printer.first
but why do you need this variable?

2023-08-06 21:32 UTC, Shabaldas commented on app/controllers/dredd/printers_controller.rb
> +      6.times { @printer.printer_maintenance.build }
what is this?
😄

2023-08-06 21:32 UTC, Shabaldas commented on app/controllers/dredd/printers_controller.rb
> +      @printer_maintenance = []
you don't need it

2023-08-06 21:32 UTC, Shabaldas commented on app/controllers/dredd/printers_controller.rb
> +    def prepare_params(product_params)
I don't understand why do you need it.
but leave for now.

2023-08-13 14:04 UTC, AndriiBuhalo commented on app/views/dredd/products/_product_option_color_values_form.erb
> +z<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
Fix

2023-08-13 14:04 UTC, AndriiBuhalo commented on app/views/dredd/products/_form.html.erb
> -          <%= primary_option.check_box :primary, { checked: true }, true, false  %>
OK

2023-08-13 14:04 UTC, AndriiBuhalo commented on app/views/dredd/products/_form.html.erb
> -          <%= secondary_option.label t("dredd.products.secondary") %>
Fix

2023-08-13 14:04 UTC, AndriiBuhalo commented on app/controllers/dredd/printers_controller.rb
> +      @printer = Printer.first
Fix

2023-10-03 11:43 UTC, Shabaldas approved these changes

2023-10-03 11:43 UTC, merged