STORM_B: Change user page in admin and add show
Shabaldas/storm_esbuild pull request #440
Opened 2024-02-17 15:58 UTC by AndriiBuhalo

![image](https://github.com/Shabaldas/storm_esbuild/assets/87270025/dac92d86-001e-4578-916c-7762247a6a63)
![image](https://github.com/Shabaldas/storm_esbuild/assets/87270025/98e55d81-d609-48c2-92bb-cd82eb4a6a81)
![image](https://github.com/Shabaldas/storm_esbuild/assets/87270025/e0a9d6fa-362c-4d08-83cf-6076924d8e53)
Change user page in admin panel:

1. Add ability to edit user name and phone (turbo frame)
2. Add page show for user
3. Cover test
4. Rubocop

2024-02-17 17:26 UTC, Shabaldas requested changes
wrong validation on User model.
for example =>
```ruby
  validates :email, uniqueness: true, on: :create
  ```
  
 You don't need to add custom validation here

2024-02-17 17:26 UTC, Shabaldas commented on app/views/dredd/_header.html.erb
> +      <span class="text-2xl text-black"><%= t("dredd.header.admin_dashboard").html_safe %></span>
why did you add it?

2024-02-17 17:26 UTC, Shabaldas commented on config/locales/en/dredd.en.yml
> +      admin_dashboard: "Admin <br> Dashboard"
????
no no no, any html tags here

2024-02-17 17:26 UTC, Shabaldas commented on spec/request/dredd/dashboard_spec.rb
> +      expect(response.body).to include('Admin <br> Dashboard')
same

2024-02-17 17:26 UTC, Shabaldas commented on spec/request/dredd/users_spec.rb
> +    let!(:user_first) { create(:user) }
no needed to call `user_first` here if tou are using one user in your rspec!
you already have a user on a top line:2

2024-02-17 17:26 UTC, Shabaldas commented on app/views/dredd/users/show.html.erb
> +      <div class="p-6 text-2xl"><%= t("dredd.users.#{@user.role}") %></div>
`<%= t("dredd.users.#{@user.role}") %>` 
how does it work, if you did't add any locals to en or ua?

2024-02-18 14:11 UTC, AndriiBuhalo commented on app/views/dredd/users/show.html.erb
> +      <div class="p-6 text-2xl"><%= t("dredd.users.#{@user.role}") %></div>
it is work)
![image](https://github.com/Shabaldas/storm_esbuild/assets/87270025/7c03a496-ca3a-46cc-b8ce-d840c2a6a4db)
![image](https://github.com/Shabaldas/storm_esbuild/assets/87270025/70cc7266-d8d1-47f8-9522-c90d2da91705)

2024-02-19 06:25 UTC, AndriiBuhalo commented on config/locales/en/dredd.en.yml
> +      admin_dashboard: "Admin <br> Dashboard"
done)

2024-02-19 06:25 UTC, AndriiBuhalo commented on app/views/dredd/_header.html.erb
> +      <span class="text-2xl text-black"><%= t("dredd.header.admin_dashboard").html_safe %></span>
deleted)

2024-02-19 06:26 UTC, AndriiBuhalo commented on spec/request/dredd/dashboard_spec.rb
> +      expect(response.body).to include('Admin <br> Dashboard')
done)

2024-02-19 06:26 UTC, AndriiBuhalo commented on spec/request/dredd/users_spec.rb
> +    let!(:user_first) { create(:user) }
done)

2024-02-20 08:31 UTC, Shabaldas approved these changes
💪

2024-02-20 08:32 UTC, merged